### ISSUE TITLE
When using singularity container

### ISSUE THREAD

**Issue by kaiyama12345679** [matsuolab/deepspeed-abci-tutorial#1]
Hi, thanks for your work, and there is one more thing I would like to know.

Would you mind providing some example of the multi-node multi-GPU distributed learning using a **singularity container** environment instead of building a python virtual environment on the ABCI host environment?

**Comment by lejelly** [comment]
Thank you for your comment.
I'm afraid it seems to be difficult to do so.
A few months ago, I also tried to use DeepSpeed with Singularity, but ultimately I couldn't succeed.

![スクリーンショット 2024-07-24 0 52 16](https://github.com/user-attachments/assets/1042c633-561a-4247-a1b7-ff1cfa627f27)

**Comment by lejelly** [comment]
This message is from ABCI staff.

**Comment by kaiyama12345679** [comment]
Oh, It is a shame that we can't use singularity for distributed learning on ABCI. Thank you for your answer.
